### ISSUE TITLE
Multi-stream support

### ISSUE THREAD

**Issue by suzukey** [suzukey/discord_transfer#1]
Currently, when multiple users start talking at the same time, the operation becomes unstable.
Therefore, we need to combine the audio streams.

**Comment by jackuma** [comment]
Looking into DiscordWerewolf.ts by TumoiYorozu may help. I will post the link below
https://github.com/TumoiYorozu/DiscordWerewolf.ts

**Comment by suzukey** [comment]
This may be what I was looking for Thank you! @jackuma 
I will work on it when I have a free.

**Comment by suzukey** [comment]
I'm sorry to have kept you waiting for a long time.
I've been busy since I started working during the day this year, so I don't know when I can get there.
