### ISSUE TITLE
[要望]コマンドでFromとToを指定できるようにしてほしい

### ISSUE THREAD

**Issue by Maximilian2022** [suzukey/discord_transfer#6]
作成者様
お世話になっております。

要望となります。
このBotを利用したいサーバーのVC数がとても多く、Wait...のまま止まってしまうため、
FromとToをID等でもよいので指定できるようにしていただけるとありがたいです。

ご一考いただけますと幸いです。

**Comment by suzukey** [comment]
@Maximilian2022 
当Botをご活用いただきありがとうございます 🙏 
Discord側の仕様でIDの他にチャンネル名も重複しないため、チャンネル名指定で実装しました！
下記のようにメッセージを送信することでご指定いただけます。

```
&trans [FromChannelName] [ToChannelName]
&transfer [FromChannelName] [ToChannelName]
```

IDで指定が必要な場合は別途Issueを作成していただけると助かります 🙇‍♂️

**Comment by Maximilian2022** [comment]
ありがとうございます！！
早速試してみます
